### ISSUE TITLE
The unauthenticated git protocol on port 9418 is no longer supported

### ISSUE THREAD

**Issue by fdansey-ostmodern** [peimanja/promtool-github-actions#4]
The command, `git ls-remote --tags --refs --sort="v:refname"  git://github.com/prometheus/prometheus` in [main.sh](https://github.com/peimanja/promtool-github-actions/blob/master/src/main.sh) fails with error,
```
Checking the latest version of Promtool
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
Failed to fetch the latest version
```

The cause is likely [this](https://github.blog/2021-09-01-improving-git-protocol-security-github/), the changes having been made permanent on 2022-03-15.

**Comment by peimanja** [comment]
fixed in #5
